config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/dashboard')

  resources :dashboard, only: [:index]

  resources :logs, only: [:index, :show]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :logs, only: [:index, :create]
    end
  end

end

app/models/atmosphere.rb
class Atmosphere < ActiveRecord::Base
  belongs_to :log
end

app/models/device.rb
require 'digest/md5'

class Device < ActiveRecord::Base
  attr_accessor :password
  validates_uniqueness_of :name
  validates_presence_of :name, :password
  
  before_create :before_create
  
  def authoricate(name, password)
    return false if name != self.name
    return false if password.nil?
    return false if Device.crypt_password(password, self.salt) != self.crypted_password
    true
  end

  def before_create
    self.salt = Device.new_salt
    self.crypted_password = Device.crypt_password(self.password, self.salt)
  end
  
  private
  def self.crypt_password(password, salt)
    Digest::MD5.hexdigest(password + salt)
  end

  def self.new_salt
    s = rand.to_s.tr('+', '.')
    s[0, if s.size > 32 then 32 else s.size end]
  end
end

app/models/humidity.rb
class Humidity < ActiveRecord::Base
  belongs_to :log
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :logs
  
  def self.exist? location_name
    self.find_by name: location_name
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  has_one :atmosphere
  has_one :humidity
  has_one :temperature
  belongs_to :location
  
  default_scope { includes(:temperature, :humidity, :atmosphere, :location) }
end

app/models/temperature.rb
class Temperature < ActiveRecord::Base
  belongs_to :log
end

app/controllers/api/v1/logs_controller.rb
class Api::V1::LogsController < ApplicationController
  protect_from_forgery except: :create

  before_filter {
    digest_authentication unless Rails.env.test? or Rails.env.development?
  }

  def index
    targets = Log.group('location_id').maximum('created_at').values
    @logs = Log.where(created_at: targets).order('id')

    render layout: false
  end

  def create
    location = Location.exist? log_params[:location]

    if location.nil?
      location = Location.create name: log_params[:location]
    end

    log = Log.new location: location

    atmosphere = Atmosphere.create value: log_params[:atmosphere]
    humidity = Humidity.create value: log_params[:humidity]
    temperature = Temperature.create value: log_params[:temperature]

    log.atmosphere = atmosphere
    log.humidity = humidity
    log.temperature = temperature

     if log.save
      WebsocketRails[:streaming].trigger "update", log.location.id
      render json: {}
    else
      render json: {}
    end
  end

  private
  def log_params
    params.permit :location, :atmosphere, :humidity, :temperature
  end

  def digest_authentication
    authenticate_or_request_with_http_basic do |name, password|
      device = Device.find_by name: name
      device.authoricate name, password
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    targets = Log.group('location_id').maximum('created_at').values
    @current_logs = Log.where(created_at: targets)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.all.order('created_at desc').first(10)
  end
  
  def show
    @log = Log.find_by id: log_params[:id]
  end
  
  private
  def log_params
    params.permit :id
  end
end

app/helpers/api/v1/logs_helper.rb
module Api::V1::LogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/dashboard/index.slim
.container
  h1 Current status
  hr

  - if @current_logs.nil?
    .alert.alert-info
       p The log does not exist.

- unless @current_logs.nil?

  - @current_logs.each do |log|
    .row.log data-location-id="#{log.location.id}"
      .container
        h2 = log.location.name
      
        .col-sm-4.panel.panel-default
          .panel-body.text-center
            p Temperature
            .h1.temperature
              = "#{log.temperature.value}"
            small ℃
      
        .col-sm-4.panel.panel-default
          .panel-body.text-center
            p Humidity
            .h1.humidity
              = "#{log.humidity.value}"
            small %
      
        .col-sm-4.panel.panel-default
          .panel-body.text-center
            p Atmosphere
            .h1.atmosphere
              = "#{log.atmosphere.value}"
            small hPa
          
        .col-xs-12
          .text-right
            span = "updated at: "
            span.updated_at = "#{log.updated_at}"

app/views/layouts/application.slim
DOCTYPE
html
  head
    title home.makky.io
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav.navbar.navbar-default(role="navigation")
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1")
            span.sr-only Toggle navigation
            - 3.times.each do |i|
              span.icon-bar

          = link_to 'home.makky.io', dashboard_index_path, class: 'navbar-brand'
          

        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav
            li
              = link_to 'Dashboard', dashboard_index_path
            li
              = link_to 'Logs', logs_path
  
    = yield
      
    .container
      hr
      .text-center
        p &copy; makky.io
    

app/views/logs/index.slim
.container
  table.table
    thead
      tr
        th id
        th Location
        th Temperature
        th Humidity
        th Atmosphere
        th Created at

    tbody
      - @logs.each do |log|
        tr
          td = link_to log.id, log_path(log)
          td = "#{log.location.name}"
          td = "#{log.temperature.value}℃"
          td = "#{log.humidity.value}%"
          td = "#{log.atmosphere.value}hPa"
          td = "#{log.updated_at}"
    

app/views/logs/show.slim
.container
  h1 = "##{@log.id}"
  hr

  .col-md-4
    .panel.panel-default
      .panel-body
        p 測定箇所
        h2 = "#{@log.location.name}"

  .col-md-4
    .panel.panel-default
      .panel-body
        p 温度
        h2 = "#{@log.temperature.value}℃"

  .col-md-4
    .panel.panel-default
      .panel-body
        p 湿度
        h2 = "#{@log.humidity.value}%"

  .col-md-4
    .panel.panel-default
      .panel-body
        p 気圧
        h2 = "#{@log.atmosphere.value}hPa"

  .col-md-4
    .panel.panel-default
      .panel-body
        p 作成
        h2 = "#{@log.created_at}"